name = "SuckAdrenaline!"
author = "WaffleIBOT"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "554b599e1619be3d6bf9dc49d2e35f02d1dec3b90b8fd618067c7bb229e41791"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
