name = "SuckAdrenaline!"
author = "WaffleIBOT"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11112ef7439a2c2071e19ff1e24f9d8bcafceff263d0739ab40dd3571fae5cde"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
