name = "SuckAdrenaline!"
author = "WaffleIBOT"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2e31c922f2ba2bfb5720b6e51f746678e567c03c124ff6312840b1b52cbd4f6"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
