name = "SuckAdrenaline!"
author = "WaffleIBOT"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89571e4a43246297706cb9cc9328503ea848d42a30c361cca25d53635202d2c8"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
